GRANT ALL ON XXTRAM_810_EDI_DATA_REC  TO XXICS;
GRANT ALL ON XXTRAM_810_EDI_DATA_TAB  TO XXICS;
GRANT ALL ON XXTRAM_EDI_810_HEADERS  TO XXICS;
GRANT ALL ON XXTRAM_EDI_810_HEADER_SEQ  TO XXICS;
GRANT ALL ON XXTRAM_EDI_810_ITEM_DTLS  TO XXICS;
GRANT ALL ON XXTRAM_EDI_810_LINE_SEQ  TO XXICS;
GRANT ALL ON XXTRAM_EDI_810_SUMMARY_DTLS  TO XXICS;
GRANT ALL ON XXTRAM_EDI_810_DATA_TBL TO XXICS;
